version: '3.4'
services: 
    app:
        build: .
        environment: 
            AWS_ACCESS_KEY_ID: minio_access_key
            AWS_SECRET_KEY_ID: minio_secret_key
            AWS_S3_ENDPOINT: s3:9000
            AWS_REGION: us-west-2
        ports: 
            - 8080:80
        depends_on: 
            - s3
        networks: 
            - pythonbridge
    s3:
        image: minio/minio
        ports: 
            - 9000:9000
        volumes:
            - storage:/data:rw
        environment: 
            MINIO_ACCESS_KEY: "minio_access_key"
            MINIO_SECRET_KEY: "minio_secret_key"
        command: server /data
        networks: 
            - pythonbridge
networks: 
    pythonbridge:
        driver: bridge
volumes: 
    storage:
        driver: local